baseURL = 'https://www.hauptvogel.dev'
languageCode = 'en-us'
title = "Nick Hauptvogel"
theme = 'hello-friend-ng'
paginate = 10

# Enable emojis
enableEmoji=true

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "02/01/2006"
  dateformNumTime = "02/01/2006 15:04"

  # Subtitle for home
  homeSubtitle = "M.Sc. Computer Science student at the University of Copenhagen, currently on exchange at the University of Toronto"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  enableThemeToggle = true
  

  # Metadata mostly used in document's head
  description = "My homepage and blog"
  keywords = "homepage, blog"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Nick Hauptvogel"
    subtitle = ""
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "nick hauptvogel"
      logoHomeLink = ""
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "posts"